data <- read.csv("C:/Users/ThinkPad/Documents/dataproject/worker_productivity.csv")
str(data)
hist(data[["actual_productivity"]],main="Histogram of Productivity Index",xlab="Productivity Index")
hist(data[["targeted_productivity"]],main="Histogram of Target Productivity",xlab="Productivity Index")
hist(data[["smv"]],main="Histogram of Standard Minute Value",xlab="Minutes Needed for Task")
hist(data[["over_time"]],main="Histogram of Over Time",xlab="Minutes of Over Time")
hist(data[["wip"]],main="Histogram of Work in Progress",xlab="Number of Unfinished Products")
hist(data[["incentive"]],main="Histogram of Financial Incentive",xlab="Bangladash Taka(BDT)",breaks=200)
hist(data[["idle_time"]],main="Histogram of Idle Time",xlab="Amount of Time When Production was Interrupted")
hist(data[["idle_men"]],main="Histogram of Idle Workers",xlab="Number of Idle Workers When Production was Interrupted")
hist(data[["no_of_style_change"]],main="Histogram of Number of Style Change",xlab="Number of Style Change")
hist(data[["no_of_workers"]],main="Histogram of Number of Workers in a Team",xlab="Number of Workers in a Team")